"""Initial schema

Revision ID: a6701545d154
Revises: 
Create Date: 2026-03-15 20:10:57.804433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6701545d154'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit_entries', schema=None) as batch_op:
        batch_op.create_index('idx_ratelimit_key_timestamp', ['key_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_entries_key_id'), ['key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_entries_timestamp'), ['timestamp'], unique=False)

    op.create_table('strategy_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_performance', schema=None) as batch_op:
        batch_op.create_index('idx_strategy_model', ['strategy_name', 'model_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_strategy_performance_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_performance_strategy_name'), ['strategy_name'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('idx_api_key_hash', ['key_hash'], unique=False)
        batch_op.create_index('idx_api_key_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_key_id'), ['key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('cost_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.create_index('idx_cost_model_provider', ['model_name', 'provider'], unique=False)
        batch_op.create_index('idx_cost_timestamp_user', ['timestamp', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entries_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entries_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entries_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entries_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entries_user_id'), ['user_id'], unique=False)

    op.create_table('usage_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_entries', schema=None) as batch_op:
        batch_op.create_index('idx_usage_model', ['model_name', 'timestamp'], unique=False)
        batch_op.create_index('idx_usage_timestamp_endpoint', ['timestamp', 'endpoint'], unique=False)
        batch_op.create_index('idx_usage_user_success', ['user_id', 'success'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_entries_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_entries_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_entries_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_entries_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_entries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_usage_entries_model_name'))
        batch_op.drop_index(batch_op.f('ix_usage_entries_error_type'))
        batch_op.drop_index(batch_op.f('ix_usage_entries_endpoint'))
        batch_op.drop_index('idx_usage_user_success')
        batch_op.drop_index('idx_usage_timestamp_endpoint')
        batch_op.drop_index('idx_usage_model')

    op.drop_table('usage_entries')
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_cost_entries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_cost_entries_request_id'))
        batch_op.drop_index(batch_op.f('ix_cost_entries_provider'))
        batch_op.drop_index(batch_op.f('ix_cost_entries_model_name'))
        batch_op.drop_index('idx_cost_timestamp_user')
        batch_op.drop_index('idx_cost_model_provider')

    op.drop_table('cost_entries')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index('idx_api_key_user_active')
        batch_op.drop_index('idx_api_key_hash')

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('strategy_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_performance_strategy_name'))
        batch_op.drop_index(batch_op.f('ix_strategy_performance_model_name'))
        batch_op.drop_index('idx_strategy_model')

    op.drop_table('strategy_performance')
    with op.batch_alter_table('rate_limit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_entries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_entries_key_id'))
        batch_op.drop_index('idx_ratelimit_key_timestamp')

    op.drop_table('rate_limit_entries')
    # ### end Alembic commands ###
