"""
Discovery adapters for autonomous intelligence sources.

Wraps TrendSignalCollector, KHGraphCollector, and Content Production Line
as discovery sources so the hourly refresh cycle populates the Nexus
knowledge base with their latest output.

C-Suite reads from Nexus KB, so this makes it aware of work product
generated by all three autonomous systems.
"""

import logging
import os
from typing import Any, Dict, Optional

from .resource_discovery import (
    DiscoveredResource,
    ResourceDiscovery,
    ResourceSource,
    ResourceType,
)

logger = logging.getLogger(__name__)


class TrendscopeDiscoverySource:
    """Wraps TrendSignalCollector as a discovery source.

    On each ``discover()`` call (hourly), fetches the latest trends,
    signals, and lifecycle data from Trendscope and writes them into
    the Nexus knowledge base.
    """

    def __init__(
        self,
        resource_discovery: ResourceDiscovery,
        knowledge_base: Any,
    ):
        self.resource_discovery = resource_discovery
        self.knowledge_base = knowledge_base
        self._collector = None

        resource_discovery.register_source(ResourceSource.TRENDSCOPE, self)
        logger.info("TrendscopeDiscoverySource registered")

    def _ensure_collector(self):
        if self._collector is None:
            from nexus.data.trend_signal_collector import TrendSignalCollector

            self._collector = TrendSignalCollector(
                knowledge_base=self.knowledge_base,
            )

    async def discover(self) -> int:
        """Collect latest Trendscope intelligence into Nexus KB."""
        self._ensure_collector()

        try:
            result = self._collector.collect_all()
        except Exception as exc:
            logger.warning("Trendscope discovery failed: %s", exc)
            return 0

        total = result.get("total_knowledge_items", 0)

        # Also register Trendscope as a discoverable API resource
        resource = DiscoveredResource(
            id="trendscope-api",
            name="Trendscope Market Intelligence",
            resource_type=ResourceType.API,
            source=ResourceSource.TRENDSCOPE,
            description=(
                "Autonomous market trend intelligence service. "
                "Collects trends from Google Trends, Reddit, Hacker News, "
                "Product Hunt. Detects anomalies, signals, and opportunities."
            ),
            url=os.environ.get("TRENDSCOPE_BASE_URL", "http://localhost:8002"),
            capabilities=[
                "trend_collection",
                "signal_detection",
                "anomaly_detection",
                "lifecycle_analysis",
                "opportunity_scoring",
            ],
            tags=["trendscope", "market-intelligence", "trends", "signals"],
            is_available=total > 0,
        )
        self.resource_discovery.register_resource(resource)

        logger.info(
            "Trendscope discovery: %d trends, %d signals, %d lifecycle items",
            result.get("trends_collected", 0),
            result.get("signals_collected", 0),
            result.get("lifecycle_collected", 0),
        )
        return total


class KHDiscoverySource:
    """Wraps KHGraphCollector as a discovery source.

    On each ``discover()`` call (hourly), fetches graph clusters and
    coverage gaps from Knowledge Harvester and writes them into the
    Nexus knowledge base.
    """

    def __init__(
        self,
        resource_discovery: ResourceDiscovery,
        knowledge_base: Any,
    ):
        self.resource_discovery = resource_discovery
        self.knowledge_base = knowledge_base
        self._collector = None

        resource_discovery.register_source(ResourceSource.KNOWLEDGE_HARVESTER, self)
        logger.info("KHDiscoverySource registered")

    def _ensure_collector(self):
        if self._collector is None:
            from nexus.data.kh_graph_collector import KHGraphCollector

            self._collector = KHGraphCollector(
                knowledge_base=self.knowledge_base,
            )

    async def discover(self) -> int:
        """Collect latest KH graph intelligence into Nexus KB."""
        self._ensure_collector()

        try:
            result = self._collector.collect_all()
        except Exception as exc:
            logger.warning("Knowledge Harvester discovery failed: %s", exc)
            return 0

        total = result.get("total_knowledge_items", 0)

        # Register KH as a discoverable API resource
        resource = DiscoveredResource(
            id="knowledge-harvester-api",
            name="Knowledge Harvester Intelligence Library",
            resource_type=ResourceType.API,
            source=ResourceSource.KNOWLEDGE_HARVESTER,
            description=(
                "Autonomous knowledge artifact library. Harvests, classifies, "
                "scores, and embeds artifacts from 37+ sources. Maintains an "
                "intelligence graph with cluster analysis and coverage gap detection."
            ),
            url=os.environ.get("KH_BASE_URL", "http://localhost:8011"),
            capabilities=[
                "artifact_harvesting",
                "classification",
                "graph_analysis",
                "coverage_gap_detection",
                "recommendation_generation",
                "semantic_search",
            ],
            tags=["knowledge-harvester", "artifacts", "intelligence-graph", "knowledge"],
            is_available=total > 0,
        )
        self.resource_discovery.register_resource(resource)

        logger.info(
            "KH discovery: %d clusters, %d coverage gaps",
            result.get("clusters_collected", 0),
            result.get("gaps_collected", 0),
        )
        return total


class ContentProductionDiscoverySource:
    """Fetches Content Production service status and publishes to Nexus KB.

    The Content Production service is a standalone service (port 8013).
    This source hits its API to surface production status, recent jobs,
    and revenue metrics into the Nexus knowledge base so other services
    (and C-Suite executives via Nexus queries) can discover what the
    production line has been doing.
    """

    def __init__(
        self,
        resource_discovery: ResourceDiscovery,
        knowledge_base: Any,
        cp_service_url: Optional[str] = None,
    ):
        self.resource_discovery = resource_discovery
        self.knowledge_base = knowledge_base
        self.cp_service_url = cp_service_url or os.environ.get(
            "CP_SERVICE_URL", "http://localhost:8013"
        )

        resource_discovery.register_source(ResourceSource.CONTENT_PRODUCTION, self)
        logger.info("ContentProductionDiscoverySource registered")

    def _fetch_json(self, url: str) -> Optional[Dict[str, Any]]:
        """GET url and return parsed JSON, or None on failure."""
        import json
        from urllib.error import URLError
        from urllib.request import Request, urlopen

        try:
            req = Request(url, headers={"Accept": "application/json"})
            with urlopen(req, timeout=5) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (URLError, OSError) as exc:
            logger.warning("ContentProduction: failed to fetch %s: %s", url, exc)
            return None
        except Exception as exc:
            logger.warning("ContentProduction: unexpected error fetching %s: %s", url, exc)
            return None

    async def discover(self) -> int:
        """Collect production line status into Nexus KB."""
        from nexus.memory.knowledge_base import KnowledgeType

        count = 0

        # Fetch production status
        status = self._fetch_json(f"{self.cp_service_url}/v1/production/status")
        if status:
            active = status.get("active_jobs", 0)
            completed = status.get("completed_jobs", 0)
            queued = status.get("queued_jobs", 0)
            fact = (
                f"Content Production Line status: {active} active, "
                f"{queued} queued, {completed} completed jobs."
            )
            self.knowledge_base.add_knowledge(
                content=fact,
                knowledge_type=KnowledgeType.FACTUAL,
                source="content_production:status",
                confidence=0.9,
                context_tags=["content_production", "status"],
            )
            count += 1

        # Fetch revenue metrics
        revenue = self._fetch_json(
            f"{self.cp_service_url}/v1/production/revenue/metrics"
        )
        if revenue:
            total_usd = revenue.get("total_revenue_usd", 0)
            total_sales = revenue.get("total_sales", 0)
            fact = (
                f"Content Production revenue: ${total_usd:.2f} from "
                f"{total_sales} sales."
            )
            self.knowledge_base.add_knowledge(
                content=fact,
                knowledge_type=KnowledgeType.FACTUAL,
                source="content_production:revenue",
                confidence=0.9,
                context_tags=["content_production", "revenue"],
            )
            count += 1

        # Register as discoverable resource
        resource = DiscoveredResource(
            id="content-production-line",
            name="Content Production",
            resource_type=ResourceType.API,
            source=ResourceSource.CONTENT_PRODUCTION,
            description=(
                "Autonomous ebook production pipeline. Generates full ebooks "
                "(DOCX, HTML, PDF, Markdown) with 60+ marketing assets per topic. "
                "10 author personas, per-chapter KH enrichment, quality gates, "
                "multi-marketplace distribution (Gumroad, Etsy, Shopify, Amazon KDP), "
                "revenue tracking, 23 pre-production roadmaps (~730 chapters)."
            ),
            url=self.cp_service_url,
            capabilities=[
                "ebook_generation",
                "blueprint_generation",
                "research_with_authority_scoring",
                "marketing_asset_generation",
                "quality_evaluation",
                "revenue_tracking",
                "marketplace_distribution",
                "author_persona_matching",
                "per_chapter_kh_enrichment",
                "pdf_docx_html_output",
                "proactive_topic_scanning",
                "per_customer_distribution",
            ],
            tags=[
                "content-production", "ebooks", "marketing", "revenue",
                "distribution", "personas", "blueprints", "quality-gates",
            ],
            is_available=status is not None,
        )
        self.resource_discovery.register_resource(resource)

        logger.info("Content Production discovery: %d knowledge items", count)
        return count
